### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.impersonate#8]
@tkimnguyen @zupo would it be possible to make a new release ?
Or to give me release rights on pypi (user : laz) ?

Thanks a lot !

**Comment by zupo** [comment]
I'm +1 for giving release rights, @tkimnguyen?

**Comment by fiterbek** [comment]
Could someone please create a 1.3 release as https://github.com/collective/collective.impersonate/commit/e4b572e0c65c1dd1af9042dcdd04b0e27d2360d6 fixes an issue that makes usage of collective.impersonate impossible in our setup (gives an error when trying to impersonate users for anything but the first time, so pretty unusable).

**Comment by thet** [comment]
@tkimnguyen @zupo ping

**Comment by thet** [comment]
maybe also give me access rights - pypi user: thet

**Comment by zupo** [comment]
@thet: invite sent

**Comment by thet** [comment]
@zupo thanks!

**Comment by thet** [comment]
@laulaz @fiterbek @zupo released

**Comment by fiterbek** [comment]
Thank you for the fast response!
